config/routes.rb
Rails.application.routes.draw do
  namespace :stats do
    resources :competitions
  end
  resources :games
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "games#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :competitions, class_name: "Stats::Competition", dependent: :restrict_with_error
end

app/models/stats.rb
module Stats
  def self.table_name_prefix
    "stats_"
  end
end

app/models/stats/competition.rb
class Stats::Competition < ApplicationRecord
  belongs_to :game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game = Game.find(params[:id])
    if @game.competitions.any?
      flash[:alert] = "Cannot delete a game that has ongoing competitions."
      redirect_to games_url, status: :unprocessable_entity
    else
      @game.destroy
      flash[:notice] = "Game was successfully deleted."
      redirect_to games_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.expect(game: [ :name, :rules_url, :shop_url ])
    end
end

app/controllers/stats/competitions_controller.rb
class Stats::CompetitionsController < ApplicationController
  before_action :set_stats_competition, only: %i[ show edit update destroy ]

  # GET /stats/competitions or /stats/competitions.json
  def index
    @stats_competitions = Stats::Competition.all
  end

  # GET /stats/competitions/1 or /stats/competitions/1.json
  def show
  end

  # GET /stats/competitions/new
  def new
    @stats_competition = Stats::Competition.new
  end

  # GET /stats/competitions/1/edit
  def edit
  end

  # POST /stats/competitions or /stats/competitions.json
  def create
    @stats_competition = Stats::Competition.new(stats_competition_params)

    respond_to do |format|
      if @stats_competition.save
        format.html { redirect_to @stats_competition, notice: "Competition was successfully created." }
        format.json { render :show, status: :created, location: @stats_competition }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stats_competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stats/competitions/1 or /stats/competitions/1.json
  def update
    respond_to do |format|
      if @stats_competition.update(stats_competition_params)
        format.html { redirect_to @stats_competition, notice: "Competition was successfully updated." }
        format.json { render :show, status: :ok, location: @stats_competition }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stats_competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stats/competitions/1 or /stats/competitions/1.json
  def destroy
    @stats_competition.destroy!

    respond_to do |format|
      format.html { redirect_to stats_competitions_path, status: :see_other, notice: "Competition was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stats_competition
      @stats_competition = Stats::Competition.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def stats_competition_params
      params.expect(stats_competition: [ :game_id, :name ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, class: "contents") do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :rules_url %>
    <%= form.text_field :rules_url, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :shop_url %>
    <%= form.text_field :shop_url, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= game.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Rules url:</strong>
    <%= game.rules_url %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Shop url:</strong>
    <%= game.shop_url %>
  </p>

</div>

app/views/games/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing game</h1>

  <%= render "form", game: @game %>

  <%= link_to "Show this game", @game, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to games", games_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/games/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Games" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Games</h1>
    <%= link_to "New game", new_game_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="games" class="min-w-full">
    <% @games.each do |game| %>
      <%= render game %>
      <p>
        <%= link_to "Show this game", game, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/games/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New game</h1>

  <%= render "form", game: @game %>

  <%= link_to "Back to games", games_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/games/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @game %>

    <%= link_to "Edit this game", edit_game_path(@game), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to games", games_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this game", @game, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Playanalog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/views/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/stats/competitions/_competition.html.erb
<div id="<%= dom_id competition %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Game:</strong>
    <%= competition.game_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= competition.name %>
  </p>

</div>

app/views/stats/competitions/_form.html.erb
<%= form_with(model: stats_competition, class: "contents") do |form| %>
  <% if stats_competition.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(stats_competition.errors.count, "error") %> prohibited this stats_competition from being saved:</h2>

      <ul>
        <% stats_competition.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :game_id %>
    <%= form.collection_select :game_id, Game.all, :id, :name, { prompt: "Select a game" }, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, value: "Competition ##{stats_competition.id}", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/stats/competitions/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing competition</h1>

  <%= render "form", stats_competition: @stats_competition %>

  <%= link_to "Show this competition", @stats_competition, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to competitions", stats_competitions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/stats/competitions/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Competitions" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Competitions</h1>
    <%= link_to "New competition", new_stats_competition_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="stats_competitions" class="min-w-full">
    <% @stats_competitions.each do |stats_competition| %>
      <%= render stats_competition %>
      <p>
        <%= link_to "Show this competition", stats_competition, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/stats/competitions/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New competition</h1>

  <%= render "form", stats_competition: @stats_competition %>

  <%= link_to "Back to competitions", stats_competitions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/stats/competitions/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @stats_competition %>

    <%= link_to "Edit this competition", edit_stats_competition_path(@stats_competition), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to competitions", stats_competitions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this competition", @stats_competition, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>